### ISSUE TITLE
fedora-upgrade terminated in the middle because of some missing config file?

### ISSUE THREAD

**Issue by praiskup** [xsuchy/fedora-upgrade#28]
I got a traceback that terminated the whole fedora-upgrade process (I believe the system is pretty consistent, as packages were upgraded to F35, though still ... some parts of the upgrade were skipped):
```
Orphaned .rpmnew and .rpmsave files:
/etc/mock/opensuse-leap-15.1-x86_64.cfg.rpmnew
/etc/mock/templates/epel-6.tpl.rpmsave
/var/lib/containers/storage/overlay/l/MSYJEI73QSVUKZ2R4ZGODSABVB/etc/adjtime.rpmsave
/var/lib/containers/storage/overlay/e5b0c49ebfe5f35b1ee74252eb9816b953b71bc60875a2fa53de1a8a74064ac7/diff/etc/adjtime.rpmsave
Delete these files (Y/n): Y
Traceback (most recent call last):
  File "/usr/sbin/rpmconf", line 105, in <module>
    main()
  File "/usr/sbin/rpmconf", line 95, in main
    rconf.run()
  File "/usr/lib/python3.10/site-packages/rpmconf/rpmconf.py", line 119, in run
    self._clean_orphan()
  File "/usr/lib/python3.10/site-packages/rpmconf/rpmconf.py", line 531, in _clean_orphan
    self._remove(file_delete)
  File "/usr/lib/python3.10/site-packages/rpmconf/rpmconf.py", line 257, in _remove
    os.unlink(conf_file)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/containers/storage/overlay/e5b0c49ebfe5f35b1ee74252eb9816b953b71bc60875a2fa53de1a8a74064ac7/diff/etc/adjtime.rpmsave'
```

**Comment by xsuchy** [comment]
This is safe precautinous. And therefore the script is run with `set -e`. I consider this a feature.
